### PR TITLE
Implement get method for MockDatabaseReference

### PR DESCRIPTION
**Pull request by Zohenn**
Implemented ```get``` method for MockDatabaseReference. This is by no means the most performant code, but it gets the job done. I basically took the existing code for ```once```, extracted most of it into a separate method and then used it to return ```MockDataSnapshot```.

I added an additional test for ```MockDataSnapshot```, but I didn't test the new method, since it's basically the same as ```once```. At least as long as it supports ```DatabaseEventType.value``` only.

### CODE REVIEW

**Comment by Zohenn** [comment]
https://github.com/sitatec/firebase_database_mocks/blob/5b541997f8d2bc68d586c0b96849077e13378da6/.github/workflows/main.yml#L33

Perhaps changing this to ```uses: subosito/flutter-action@v2``` might help? Or you could try to build on Ubuntu instead of MacOS.

**Comment by sitatec** [comment]
Thanks @Zohenn for the PR. We need to resolve one conflict to merge it.

**Comment by Zohenn** [comment]
@sitatec done. I will try to implement other methods, though it needs a bit more work in order to not repeat the code. It should be done better than in this PR, so you can actually test this. I suppose you're not working on anything related to this package at the moment?

**Comment by sitatec** [comment]
@Zohenn no, I haven't worked on something related to this package for a while.
I will try to write some unit tests on this PR before merging to not reduce the coverage

**Comment by Zohenn** [comment]
@sitatec I can do it too, will get it done today. The coverage will still decrease a bit anyway. It's just a metric after all.

**Comment by Zohenn** [comment]
@sitatec Could you run Codecov now?
I have also added ```coverage``` directory from Android Studio to ```.gitignore``` and removed ```pubspec.lock```, as per https://dart.dev/guides/libraries/private-files#the-rules.

**Comment by Zohenn** [comment]
@sitatec Could you please take a look at this, or at least publish a new version to pub.dev with contents of #6 in it? It prevents me (and probably others) from updating other dependencies.

**Review by sitatec — APPROVED** [review]

**Comment by Zohenn** [comment]
Huge thanks man!

**Comment by sitatec** [comment]
I just published the new version to pub.dev

**Pull request merged**
